---
- name: Configure Jenkins Server
  hosts: jenkins_server
  become: yes
  vars:
    jenkins_repo_url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    jenkins_key_url: "https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key"

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Java 17 (Amazon Corretto)
      dnf:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Download Jenkins repository
      get_url:
        url: "{{ jenkins_repo_url }}"
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: "{{ jenkins_key_url }}"

    - name: Install Jenkins, Git, and Docker
      dnf:
        name:
          - jenkins
          - git
          - docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Add 'jenkins' user to 'docker' group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Jenkins to apply group changes
      service:
        name: jenkins
        state: restarted
